language: cpp

sudo: required

dist: bionic

compiler:
  - gcc

env:
  global:
    - INSTALL_DIR=~/mylibs
    - CXXFLAGS="-Werror"

script:
  - mkdir build_tmp && cd build_tmp
  - CXX=g++-5 && CC=gcc-5
  - cmake -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR $TRAVIS_BUILD_DIR
  - make
  - make install
  - make examples

before_script:
  - cat /etc/apt/sources.list
  - cat /etc/apt/sources.list.d/*
  - sudo apt-add-repository multiverse
  - sudo apt-get update -qq
  - sudo dpkg --configure -a
  - sudo apt-get install -f -qq
  - sudo dpkg --get-selections | grep hold || { echo "All packages OK."; }
  - sudo apt-get install -q -y cmake-data cmake
  - sudo apt-get install -qq build-essential g++-5
  - gcc-5 --version && g++-5 --version # 5.5.0
  - apt-cache search nvidia-*
  - sudo apt-get install -qq nvidia-common
  - sudo apt-get install -qq nvidia-cuda-dev nvidia-cuda-toolkit # 9.1.85
  - sudo apt-get install -qq libboost-dev # 1.65.1
  - sudo find /usr/ -name libcuda*.so

after_script:
  - ls -halR $INSTALL_DIR

